version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
    depends_on:
      mysql:
        condition: service_healthy

  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apache
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./student_code/hncwebsa1:/home/hncwebsa1/website
      - ./student_code/hncwebsa2:/home/hncwebsa2/website
      - ./student_code/hncwebsa3:/home/hncwebsa3/website
      - ./student_code/hncwebsa4:/home/hncwebsa4/website
      - ./student_code/hncwebsa5:/home/hncwebsa5/website
      - ./student_code/hncwebsa6:/home/hncwebsa6/website
      - ./student_code/hncwebsa7:/home/hncwebsa7/website
      - ./student_code/hncwebsa8:/home/hncwebsa8/website
      - ./student_code/hncwebsa9:/home/hncwebsa9/website
      - ./student_code/hncwebsa10:/home/hncwebsa10/website
      - ./student_code/hncwebsa11:/home/hncwebsa11/website
      - ./student_code/hncwebsa12:/home/hncwebsa12/website
      - ./student_code/hncwebsa13:/home/hncwebsa13/website
      - ./student_code/hncwebsa14:/home/hncwebsa14/website
      - ./student_code/hncwebsa15:/home/hncwebsa15/website
      - ./student_code/hncwebsa16:/home/hncwebsa16/website
      - ./student_code/hncwebsa17:/home/hncwebsa17/website
      - ./student_code/hncwebsa18:/home/hncwebsa18/website
      - ./student_code/hncwebsa19:/home/hncwebsa19/website
      - ./student_code/hncwebsa20:/home/hncwebsa20/website
      - ./student_code/hncwebsa21:/home/hncwebsa21/website
      - ./student_code/hncwebsa22:/home/hncwebsa22/website
      - ./student_code/hncwebsa23:/home/hncwebsa23/website
      - ./student_code/hncwebsa24:/home/hncwebsa24/website
      - ./student_code/hncwebsa25:/home/hncwebsa25/website
      - ./apache:/etc/apache2/sites-enabled
      - ./config/sshd_config:/etc/ssh/sshd_config
      - ./setup_flag:/setup_flag
      - ./othershome:/home/othershome

    ports:
      - "80:80"
      - "2222:22"
    networks:
      - backend
      - frontend
    depends_on:
      mysql:
        condition: service_healthy

networks:
  backend:
  frontend:

volumes:
  mysql_data:
  setup_flag:

