version: '3.8'

services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./persistent_folders/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: http://192.168.1.241/phpmyadmin/
    expose:
      - "80"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apache
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./persistent_folders/home:/home
      - ./persistent_folders/apache:/etc/apache2/sites-enabled
      - ./persistent_folders/setup_flag:/setup_flag
      - ./users_csv/csv:/root/users_csv
      - ./scripts/sync_users.sh:/root/sync_users.sh
    ports:
      - "80:80"
      - "2222:22"
    networks:
      - backend
      - frontend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
      
networks:
  backend:
  frontend:

volumes:
  mysql_data:
  setup_flag:
