services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: http://192.168.1.241/phpmyadmin/ #change IP or enter a domain here. The `/` at the end is CRUCIAL !
    expose:
      - "80"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apache
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - apache_home:/home
      - apache_sites:/etc/apache2/sites-enabled
    ports:
      - "80:80"
      - "22:22"
    networks:
      - backend
      - frontend
    depends_on:
      mysql:
        condition: service_healthy
      
networks:
  backend:
  frontend:

volumes:
  mysql_data:
  apache_home:
  apache_sites:
