name: "Download Button Action"
on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for any tag starting with 'v'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Update README with download button
        env:
          GITHUB_USER: "kennyHH"
          REPO: "AWS"
          FORMAT: "zip"
          VERSION: "${{ steps.get-latest-tag.outputs.tag }}"
          COLOR: "blue"
          BEGIN_TAG: "<!-- BEGIN LATEST DOWNLOAD BUTTON -->"
          END_TAG: "<!-- END LATEST DOWNLOAD BUTTON -->"
        run: |
          BUTTON="[![Download ${{ env.FORMAT }}](https://custom-icon-badges.demolab.com/badge/-Download-${{ env.COLOR }}?style=for-the-badge&logo=download&logoColor=white \"Download ${{ env.FORMAT }}\")](${{ github.server_url }}/${{ env.GITHUB_USER }}/${{ env.REPO }}/archive/refs/tags/${{ env.VERSION }}.${{ env.FORMAT }})"
          sed -i "/${{ env.BEGIN_TAG }}/,/${{ env.END_TAG }}/c\\${{ env.BEGIN_TAG }}\n${BUTTON}\n${{ env.END_TAG }}" README.md

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"

      - name: Commit changes
        if: steps.git-check.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v7
        with:
          message: "docs(readme): Bump download button version to ${{ steps.get-latest-tag.outputs.tag }}"
          default_author: github_actions
          branch: main
